# -*- coding: utf-8 -*-
"""TY_data_fetching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfaaSjgButjAWDlCp3pETaa67ENlkttX
"""

pip install google-api-python-client pandas isodate python-dateutil emoji langdetect

import os
import time
import re
import pandas as pd
import emoji
import isodate
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from langdetect import detect

API_KEY = 'AIzaSyAGQfUWbTxS0lJl9wwJ3XIGqNTqbGMaghk'
youtube = build('youtube', 'v3', developerKey=API_KEY)

"""# config"""

TARGET_VIDEOS = 3000
VIDEOS_PER_CHANNEL = 6
MAX_CHANNELS = 500
VIDEO_BATCH = 50

MAX_DURATION = 900
SHORT_LIMIT = 60

SEED_QUERIES = {
    "opinion":["things i hate about modern life","truth nobody talks about india","stop doing this if you want success"],
    "hook_content": ["watch this before you scroll","you need to see this today","this video is for you"],
    "challenge": ["30 day challenge results","i tried this for 7 days","what happens if you do this daily"],
    "mistakes": ["common mistakes people make daily","biggest mistakes students make"],
    "advice": [ "listen carefully this will help you","if you are struggling watch this", "important message for students"],
    "transformation": ["before vs after transformation","my life changed after this","real transformation journey india"],
    "questions":[ "what would you do in this situation","what is your biggest goal", "have you ever felt like this"]
}

# CACHE (reduce API calls)
video_cache = {}
channel_cache = {}
search_cache = {}

"""# clean filter"""

# Detect English

def is_english(text):
    try:
        return detect(text) == "en"
    except:
        return False

# clean description

def clean_text_pipeline(title,description):
    text = title + " " + (description or "")

    text = re.sub(r'http\S+', '', text) # remove link
    text = re.sub(r'\d{1,2}:\d{2}', '', text) # remove timestamp
    text = re.sub(r'\s+', ' ', text) # remove white space

    return text.strip()

# extract hashtag

def extract_hashtag(text):
    hashtags = re.findall(r"#\w+", text)
    return hashtags

# Duration parser

def parse_duration(d):
    try:
        return int(isodate.parse_duration(d).total_seconds())
    except:
        return None

# Emoji count

def count_emoji(text):
    return sum(1 for c in text if c in emoji.EMOJI_DATA)

"""# video search"""

def search_video(query):
    if query in search_cache:
        return search_cache[query]

    try:
        req = youtube.search().list(
            part="id,snippet",
            q=query,
            type="video",
            maxResults=20,
            regionCode="IN",
            relevanceLanguage="en"
        )
        res = req.execute()
        ids = [v["id"]["videoId"] for v in res.get("items", [])]
        ids = list(set(ids))
        search_cache[query] = ids
        print(f"Query '{query}' → {len(ids)}")
        return ids

    except HttpError as e:
        print("Quota or API error:", e)
        return []

"""# video details"""

def get_video_details(video_ids, niche):
    rows = []

    for i in range(0, len(video_ids), VIDEO_BATCH):
        batch = video_ids[i:i+VIDEO_BATCH]

        new_batch = [v for v in batch if v not in video_cache]

        if new_batch:
            req = youtube.videos().list(
                part="snippet,statistics,contentDetails",
                id=",".join(new_batch)
            )
            res = req.execute()

            for v in res.get("items", []):
                video_cache[v["id"]] = v

        # PROCESS FROM CACHE
        for vid in batch:
            v = video_cache.get(vid)
            if not v:
                continue

            sn = v["snippet"]
            st = v.get("statistics",{})
            cd = v.get("contentDetails",{})

             # Duration Filter

            duration = parse_duration(cd.get("duration"))
            if duration is None:
                continue
            if duration > MAX_DURATION or duration < 5:
                continue

            content_type = "short" if duration <= SHORT_LIMIT else "video"

            # Caption

            title = sn.get("title","")
            description = sn.get("description","")
            full_text_raw = title + " " + description

            # Apply filter

            if not full_text_raw or len(full_text_raw.strip()) < 30:
                continue

            if not is_english(full_text_raw):
                continue

            # Hashtag
            hashtags = extract_hashtag(full_text_raw)
            hashtag_count = len(hashtags)

            # Engagement
            views = int(st.get("viewCount",0))
            likes = int(st.get("likeCount",0))
            comments = int(st.get("commentCount",0))

            if views < 1000 or likes < 10:
                continue

            # clen text
            full_text_clean = clean_text_pipeline(title,description)

            rows.append({
                "post_id": v["id"],
                "channel_id": sn["channelId"],

                # Raw text
                "caption_raw": full_text_raw,

                #clean text
                "full_text_clean": full_text_clean,

                "hashtags": " ".join(hashtags),
                "hashtag_count": hashtag_count,
                "emoji_count": count_emoji(full_text_raw),

                "likes": likes,
                "views": views,
                "comments": comments,

                "duration_sec": duration,
                "content_type": content_type,
                "category_id": sn.get("categoryId"),
                "timestamp": sn["publishedAt"],
            })

    print(f"[DEBUG] Rows after filtering: {len(rows)}")

    return rows

"""# Channel expansion"""

def get_uploads(channel_id):
    if channel_id in channel_cache:
        return channel_cache[channel_id]

    try:
        req = youtube.channels().list(
            part="contentDetails",
            id=channel_id
        )
        res = req.execute()

        if not res.get("items"):
            return None

        playlist = res["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]
        channel_cache[channel_id] = playlist
        return playlist

    except Exception as e:
        return None

def expand_channel(channel_id):
    vids = []

    if channel_id in channel_cache:
        return vids

    playlist = get_uploads(channel_id)

    if not playlist:
        return vids

    next_page = None

    try:
        while len(vids) < VIDEOS_PER_CHANNEL:
            req = youtube.playlistItems().list(
                part="contentDetails",
                playlistId=playlist,
                maxResults=50,
                pageToken=next_page
            )
            res = req.execute()

            for v in res.get("items", []):
                vid = v["contentDetails"]["videoId"]
                vids.append(vid)

                if len(vids) >= VIDEOS_PER_CHANNEL:
                    break

            next_page = res.get("nextPageToken")

            if not next_page:
                break

    except:
        pass

    return list(set(vids))

"""# channel stats"""

def fetch_channel_stats(channel_ids):
    stats = {}

    for i in range(0, len(channel_ids), 50):
        batch = channel_ids[i:i+50]

        req = youtube.channels().list(
            part="statistics",
            id=",".join(batch)
        )
        res = req.execute()

        for c in res.get("items", []):
            stats[c["id"]] = {
                "followers_count": int(c["statistics"].get("subscriberCount", 0) or 0),
                "total_posts": int(c["statistics"].get("videoCount", 0))
            }

    return stats

"""# Main Pipeline"""

def build_dataset():
    all_video_ids = set()
    channel_ids = set()
    channel_niche_map = {}

    print("\n STEP 1: SEED SEARCH ")
    seed_query_results = {}

    for niche, queries in SEED_QUERIES.items():
        for q in queries:
            vids = search_video(q)
            seed_query_results[q] = vids
            all_video_ids.update(vids)

    print(f"Seed videos: {len(all_video_ids)}")

    print("\n STEP 2: GET CHANNELS ")
    seed_data = []

    # fetch seed data per niche
    for niche, queries in SEED_QUERIES.items():
        niche_video_ids = []

        for q in queries:
            vids = seed_query_results[q]
            niche_video_ids.extend(vids)

        data = get_video_details(niche_video_ids, niche)
        if not data:
            continue

        seed_data.extend(data)

        # map channel  niche
        for d in data:
            channel_ids.add(d["channel_id"])

            if d["channel_id"] not in channel_niche_map:
                channel_niche_map[d["channel_id"]] = niche

    print(f"Channels found: {len(channel_ids)}")

    print("\n STEP 3: EXPAND CHANNELS ")
    expanded_ids = set()

    for i, ch in enumerate(list(channel_ids)[:MAX_CHANNELS]):
        vids = expand_channel(ch)
        expanded_ids.update(vids)

        if len(expanded_ids) >= TARGET_VIDEOS * 1.5:
            break

        if i % 50 == 0:
            print(f"Expanded from {i} channels {len(expanded_ids)} videos")

    print(f"Total expanded videos: {len(expanded_ids)}")

    print("\n STEP 4: FINAL VIDEO DETAILS ")

    # BATCH FETCH
    expanded_ids = list(expanded_ids)
    all_video_data = get_video_details(expanded_ids, "temp")

    final_data = []

    for d in all_video_data:
        ch = d["channel_id"]
        niche = channel_niche_map.get(ch, "general")
        d["niche"] = niche
        final_data.append(d)

    df = pd.DataFrame(final_data).drop_duplicates("post_id")
    df = df[df["caption_raw"].str.len() > 30]
    df = df[df["views"] > 1000]
    df = df[df["likes"] > 10]

    df = df.sample(n=min(TARGET_VIDEOS, len(df)), random_state=42)

    print("\nSTEP 5: CHANNEL STATS ")
    ch_stats = fetch_channel_stats(df["channel_id"].unique())

    df["followers_count"] = df["channel_id"].map(lambda x: ch_stats.get(x, {}).get("followers_count", 0))
    df["total_posts"] = df["channel_id"].map(lambda x: ch_stats.get(x, {}).get("total_posts", 0))


    print("\n FINAL DEBUG ")
    print("Rows:", len(df))
    print("Unique channels:", df["channel_id"].nunique())
    print("Short vs Video:\n", df["content_type"].value_counts())
    print("\nNiche Distribution:\n", df["niche"].value_counts())

    df.to_csv("dataset_5k.csv", index=False)
    print("Dataset saved!")

    return df

# RUN
build_dataset()

df = pd.read_csv("/content/dataset_5k.csv", encoding="latin1")

def fix_text(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except:
        return text

df = df.applymap(lambda x: fix_text(x) if isinstance(x, str) else x)

df.to_csv("dataset.csv", index=False, encoding="utf-8-sig")

