# -*- coding: utf-8 -*-
"""caption_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzdTcZYfod9MUBs5ufsgT4NAxWF6_GO2
"""

import pandas as pd
import numpy as np

df1 = pd.read_csv("/content/drive/MyDrive/dataset 1.csv")
df2 = pd.read_csv("/content/drive/MyDrive/dataset 2.csv")
df3 = pd.read_csv("/content/drive/MyDrive/dataset 3.csv")
df4 = pd.read_csv("/content/drive/MyDrive/dataset 4.csv")

df = pd.concat([df1,df2,df3,df4], ignore_index=True)
df.shape

df = df.drop_duplicates(subset="post_id")

df.shape

df.head()

df.to_csv("Final_merge_Data.csv", index=False,encoding="utf-8-sig")

"""# generate labels"""

!pip install emoji

import pandas as pd
import numpy as np
import re
import emoji

df = pd.read_csv("/content/drive/MyDrive/Final_merge_Data .csv")

df.head()

df.columns

# clean text col
def clean_caption(text):
    if not isinstance(text,str):
        return ""

    # remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # remove timestamps like 12:30
    text = re.sub(r"\b\d{1,2}:\d{2}\b", "", text)

    # remove hashtags
    text = re.sub(r"#\w+", "", text)

    # remove invisible unicode chars
    text = re.sub(r"[\u200b-\u200d\uFEFF]", "", text)

    # reduce excessive punctuation
    text = re.sub(r'([!?.,])\1{3,}', r'\1\1', text)

    # normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df['full_text_clean'] = df['full_text_clean'].apply(clean_caption)

df = df[df['full_text_clean'].str.len() > 15]

df.shape

"""# Handling outliers"""

import matplotlib.pyplot as plt

cols = ["views", "likes", "comments", "followers_count"]

for col in cols:

    plt.figure(figsize=(6,4))

    plt.boxplot(df[col])

    plt.title(col)

    plt.show()

# clip outliers
for col in cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)

    df[col] = df[col].clip(lower, upper)

# log transform
df["views_log"] = np.log1p(df["views"])
df["likes_log"] = np.log1p(df["likes"])
df["comments_log"] = np.log1p(df["comments"])
df["followers_log"] = np.log1p(df["followers_count"])

"""# After clipping"""

for col in cols:

    plt.figure(figsize=(6,4))

    plt.boxplot(df[col])

    plt.title(col)

    plt.show()

"""# engagement rate"""

df["ER"] = (df["likes"] + df["comments"]) / df["views"]

df["ER"]

# clip ER
df["ER"] = df["ER"].clip(0, df["ER"].quantile(0.99))

df["engagement_score"] = (
    df["ER"]
    .rank(pct=True)
)

df["engagement_score"].describe()

df.to_csv("Caption_training_data.csv",index=False )

"""# Feature Engg"""

import pandas as pd
import numpy as np

df1 = pd.read_csv("/content/drive/MyDrive/Caption_training_data.csv")

df1["full_text_clean"] = df1["full_text_clean"].fillna("")
df1["hashtags"] = df1["hashtags"].fillna("")

"""# Caption length"""

df1["caption_length"] = (df1["full_text_clean"].str.split().str.len())

"""# density feature"""

df1["emoji_density"] = df1["emoji_count"]/(df1["caption_length"] + 1)

df1["hashtag_density"] = df1["hashtag_count"]/(df1["caption_length"] + 1)

"""# sentiment score"""

from textblob import TextBlob

def get_sentiment(text):

    polarity = TextBlob(text).sentiment.polarity

    return polarity

df1["sentiment"] = (
    df1["full_text_clean"]
    .apply(get_sentiment)
)

"""# Hook, CTA features"""

curiosity_hooks = ["wait", "watch till end","don't skip", "you won't believe","what happened next","unexpected","plot twist","ending","secret","finally"]
relatable_hooks = [ "pov","bro","every girl","every boy","middle class","real struggle","only legends","relatable","parents","best friend"]
emotional_hooks = ["cry","heartbroken","miss you","sad","emotional","pain","love","broken"]
hype_hooks = ["viral","crazy","insane","omg","wtf","unbelievable","legendary","fire"]
cta_words = ["comment","share","follow","save","tag","send this"]

def count_keyword(text,keyword):
    text = text.lower()

    return sum(kw in text for kw in keyword)

df1["curiosity_score"] = df1["full_text_clean"].apply(lambda x: count_keyword(x,curiosity_hooks))
df1["relatable_score"] = df1["full_text_clean"].apply(lambda x: count_keyword(x,relatable_hooks))
df1["emotional_score"] = df1["full_text_clean"].apply(lambda x: count_keyword(x,emotional_hooks))
df1["hype_score"] = df1["full_text_clean"].apply(lambda x: count_keyword(x,hype_hooks))
df1["cta_score"] = df1["full_text_clean"].apply(lambda x: count_keyword(x,cta_words))

df1["post_log"] = np.log1p(df1["total_posts"])

"""# time feature"""

df1["timestamp"] = pd.to_datetime(df1["timestamp"])

df1["hour"] = df1["timestamp"].dt.hour
df1["weekday"] = df1["timestamp"].dt.weekday

df1["is_weekend"] = df1["weekday"].apply(lambda x: 1 if x in [5, 6] else 0)

import re

def clean_hashtag(text):
    hashtags = re.findall(r"#\w+", str(text))

    cleaned = []
    for tag in hashtags:
        tag = tag.lower().strip()
        tag = tag.replace("#","")

        if tag:
            cleaned.append(tag)

    cleaned = list(dict.fromkeys(cleaned))

    return " ".join(cleaned)

df1["hashtags"] = df1["hashtags"].apply(clean_hashtag)

caption_text = [
    "passage:" + str(text) for text in df1["full_text_clean"]
]

hashtag_text = [
    "passage:" + str(text) for text in df1["hashtags"]
]

"""# Generate Embeddings"""

from sentence_transformers import SentenceTransformer

# LOAD MULTILINGUAL E5 MODEL

E5_model = SentenceTransformer("intfloat/multilingual-e5-base")

cap_emb = E5_model.encode(
    caption_text,
    show_progress_bar=True,
    normalize_embeddings=True,
    batch_size= 64
)

hash_emb = E5_model.encode(
    hashtag_text,
    show_progress_bar=True,
    normalize_embeddings=True,
    batch_size= 64
)

"""# similarity"""

similarity_scores = np.sum(cap_emb * hash_emb, axis=1)

df1["caption_hashtag_similarity"] = similarity_scores

df1.columns

df1.drop(['post_id','channel_id','caption_raw', 'full_text_clean', 'hashtags',
          'likes', 'views', 'comments', 'content_type', 'category_id',
          'timestamp', 'niche','followers_count', 'total_posts', 'views_log', 'likes_log',
          'comments_log','ER'],axis=1,inplace=True)

df1.columns

cap_df = pd.DataFrame(
    cap_emb,
    columns=[f"cap_emb_{i}" for i in range(cap_emb.shape[1])]
)

hash_df = pd.DataFrame(
    hash_emb,
    columns=[f"hash_emb_{i}" for i in range(hash_emb.shape[1])]
)

df1 = pd.concat([df1,cap_df,hash_df],axis=1)

from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,r2_score

x = df1.drop(["engagement_score"],axis=1)
y = df1["engagement_score"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.01,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(x_train,y_train)

pred = xgb_model.predict(x_test)

mae = mean_absolute_error(y_test,pred)
rmse = root_mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)

print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R2   : {r2:.6f}")

from scipy.stats import spearmanr

corr, _ = spearmanr(
    y_test,
    pred
)

print("Spearman:", corr)

!pip install catboost

from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.03,
    depth=4,
    loss_function='RMSE',
    eval_metric='R2',
    random_seed=42,
    l2_leaf_reg=10,
    random_strength=2,
    verbose=100
)

cat_model.fit(x_train,y_train,eval_set=(x_test, y_test),use_best_model=True)

pred = cat_model.predict(x_test)

mae = mean_absolute_error(y_test,pred)
rmse = root_mean_squared_error(y_test,pred)
r2 = r2_score(y_test,pred)

print(f"MAE  : {mae:.6f}")
print(f"RMSE : {rmse:.6f}")
print(f"R2   : {r2:.6f}")

from scipy.stats import spearmanr

corr, _ = spearmanr(
    y_test,
    pred
)

print("Spearman:", corr)

import joblib

joblib.dump(x_train.columns.tolist(), "feature_columns.pkl")

E5_model.save("E5_model")
joblib.dump(cat_model,"ER_potential.pkl")

